# Generated by Django 3.1.1 on 2020-12-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=2000, null=True)),
                ('slug', models.SlugField(max_length=2000, null=True)),
                ('email', models.EmailField(max_length=2000, null=True, unique=True)),
                ('phone', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, default='/default.png', null=True, upload_to='staff/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
