# Generated by Django 3.1.1 on 2020-12-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(max_length=2000, null=True, unique=True),
        ),
    ]
